project:
  type: website
  output-dir: docs
  resources:
    - "**/*pdf"
    - "asset/**/*png"
    - "asset/**/*jpg"

  preview:
    port: 9595
    browser: false
  render:
    - '*.qmd'
    - 'lenouveautaxi3/**/*.qmd'
    - 'af-nice-b1-2/**/*.qmd'
    - 'defi*/**/*.qmd'
    - 'archive/**/*.qmd'


website:
  title: "Bonjour!"
  favicon: profile.jpg
  navbar:
    logo: profile.jpg
    # background: '#291B10'
    left:
      - text: "Défi 4"
        icon: book
        href: defi4.qmd
      - text: "Défi 3"
        icon: book
        href: defi3.qmd
      - text: "AF Nice"
        icon: backpack
        href: af-nice-b1.qmd
      - text: "Le Nouveau Taxi 3"
        icon: youtube
        href: le-nouveau-taxi-3.qmd
    right:
      - text: "L'espace Virtuel"
        icon: clouds-fill
        href: "https://espacevirtuel.emdl.fr"
      - text: Archive
        icon: archive
        href: archive.qmd
format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 3
    theme:
      # - lumen
      # - united
      # - yeti
      # - sandstone
      - sandstone
      - custom.scss
    css: 
      - styles.css
    



